services:
  - type: web
    name: skilloryx
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: skilloryx
          property: host
