services:
  - type: web
    name: skilloryx
    runtime: python3
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: daphne main.asgi:application --bind 0.0.0.0 --port $PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: skilloryx
          property: host
